# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.AddField(
            model_name='reviews',
            name='book_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_book', to='books_app.Books'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='books_app.userDB'),
        ),
    ]
